# ~ is None

type : 
    C :
        - standard_scaler
        - svc
    R :
        - standard_scaler
        - svc

svc :
    C : 1
    gamma : auto
    decision_function_shape : ovr

# RandomForestClassifier
rf :
    n_estimators : 500
    criterion : gini
    max_depth : 5
    min_samples_split : 2
    min_samples_leaf : 1


